language: csharp
solution: sqldoc.sln

script:
  - xbuild /p:Configuration=Release sqldoc.sln
  #- mono ./packages/xunit.runner.console.*/tools/net452/xunit.console.exe ./tests/bin/Release/tests.dll
  - mono ./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe -register:user -target:"./packages/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe" -targetargs:".\tests\bin\Release\tests.dll -noshadow" -filter:"+[sqldoc*]* -[tests*]*" -output:"coverage.xml"
 
after_script:
  - bash <(curl -s https://codecov.io/bash)