version: '0.0.{build}'
image: Visual Studio 2015

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install "msbuild-sonarqube-runner" -y

build_script:
- SonarScanner.MSBuild.exe begin /k:"sqldoctor" /d:sonar.organization="bobinskim-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="7cae712236e78e474beddcfe331790562fc2c6fc"
- msbuild sqldoc.sln
- OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.3.1/tools/net452/xunit.console.exe" -targetargs:".\tests\bin\Debug\tests.dll -noshadow" -filter:"+[sqldoc*]* -[tests*]* -[sqldoc*]SqlDoctor.Program" -output:".\coverage.xml"
- SonarScanner.MSBuild.exe end /d:sonar.login="7cae712236e78e474beddcfe331790562fc2c6fc"
- codecov -f "coverage.xml"
