version: '1.0.{build}'
image: Visual Studio 2015

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: sqldoc.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.3.1/tools/net452/xunit.console.exe" -targetargs:".\tests\bin\Debug\tests.dll -noshadow" -filter:"+[sqldoc*]* -[tests*]*" -output:".\coverage.xml"
- codecov -f "coverage.xml"
