name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get version
      uses: olegtarasov/get-tag@v2.1
      id: tagName
      with:
        tagRegex: "v(.*)"
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*   
    - name: Build
      run: dotnet build
    - name: Pack NuGet
      run: |
        dotnet pack ./sqldoc.csproj --no-build -p:PackageVersion=${{ steps.tagName.outputs.tag }} --output .
    - name: PushGithub
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
